#let entry-list-1 = (
  (
    title: "Pre-Reveal Reflection",
    type: "identify",
    date: datetime(year: 2024, month: 4, day: 20),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Jin",
    body: 1,
  ),
  (
    title: "Reveal Video Thoughts",
    type: "identify",
    date: datetime(year: 2024, month: 4, day: 27),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Jin",
    body: 4,
  ),
  (
    title: "Game Challenge - Rules Analysis",
    type: "identify",
    date: datetime(year: 2024, month: 4, day: 30),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Jin",
    body: 7,
  ),
  (
    title: "Game Challenge - Strategy Analysis",
    type: "identify",
    date: datetime(year: 2024, month: 4, day: 30),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Jin",
    body: 17,
  ),
  (
    title: "High Stakes Season Planning",
    type: "management",
    date: datetime(year: 2024, month: 4, day: 30),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Jin",
    body: 19,
  ),
  (
    title: "June Planning",
    type: "management",
    date: datetime(year: 2024, month: 6, day: 14),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Rory",
    body: 21,
  ),
  (
    title: "Overall Robot Plan v1",
    type: "brainstorm",
    date: datetime(year: 2024, month: 6, day: 14),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Jin",
    witnessed: "Anders",
    body: 22,
  ),
  (
    title: "Overall Robot Plan v1",
    type: "select",
    date: datetime(year: 2024, month: 6, day: 15),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Jin",
      "Rory",
      "Makhi",
    ),
    designed: "Rory",
    witnessed: "Ishika",
    body: 25,
  ),
  (
    title: "Overall Robot Plan v1",
    type: "plan",
    date: datetime(year: 2024, month: 6, day: 15),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Jin",
      "Rory",
      "Makhi",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 27,
  ),
  (
    title: "Kanban Board",
    type: "management",
    date: datetime(year: 2024, month: 6, day: 16),
    attendance: ("Ajibola", "Ishika", "Eric", "Rory", "Makhi"),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 28,
  ),
  (
    title: "Drivetrain v1",
    type: "identify",
    date: datetime(year: 2024, month: 6, day: 16),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 31,
  ),
  (
    title: "Drivetrain v1",
    type: "understand",
    date: datetime(year: 2024, month: 6, day: 16),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Jin",
    witnessed: "Eric",
    body: 33,
  ),
  (
    title: "Drivetrain v1 - Drive Configurations",
    type: "brainstorm",
    date: datetime(year: 2024, month: 6, day: 22),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Eric",
    body: 35,
  ),
  (
    title: "Drivetrain v1 - Drive Configurations",
    type: "select",
    date: datetime(year: 2024, month: 6, day: 22),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Makhi",
    witnessed: "Ishika",
    body: 37,
  ),
  (
    title: "Drivetrain v1 - Wheel Types",
    type: "brainstorm",
    date: datetime(year: 2024, month: 6, day: 23),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Rory",
    body: 39,
  ),
  (
    title: "Drivetrain v1 - Wheel Types",
    type: "select",
    date: datetime(year: 2024, month: 6, day: 24),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ishika",
    witnessed: "Eric",
    body: 43,
  ),
  (
    title: "Drivetrain v1 - Gear Ratio",
    type: "brainstorm",
    date: datetime(year: 2024, month: 6, day: 28),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Makhi",
    witnessed: "Jin",
    body: 45,
  ),
  (
    title: "Drivetrain v1 - Gear Ratio",
    type: "select",
    date: datetime(year: 2024, month: 6, day: 29),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Rory",
    witnessed: "Ishika",
    body: 47,
  ),
  (
    title: "Drivetrain v1",
    type: "plan",
    date: datetime(year: 2024, month: 6, day: 29),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 49,
  ),
  (
    title: "Game Manual v1.0 Update",
    type: "identify",
    date: datetime(year: 2024, month: 7, day: 1),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Ishika",
    body: 57,
  ),
  (
    title: "July & August Planning",
    type: "management",
    date: datetime(year: 2024, month: 7, day: 26),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 61,
  ),
  (
    title: "Drivetrain v1",
    type: "build",
    date: datetime(year: 2024, month: 7, day: 26),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Makhi",
    body: 63,
  ),
  (
    title: "GitHub Workflows",
    type: "program",
    date: datetime(year: 2024, month: 8, day: 3),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 73,
  ),
  (
    title: "The Minnesota Signature Event Observations",
    type: "identify",
    date: datetime(year: 2024, month: 8, day: 6),
    attendance: ("Jin", "Ishika", "Eric"),
    designed: "Jin",
    witnessed: "Ishika",
    body: 79,
  ),
  (
    title: "Overall Robot Plan v2",
    type: "brainstorm",
    date: datetime(year: 2024, month: 8, day: 6),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 86,
  ),
  (
    title: "Overall Robot Plan v2",
    type: "select",
    date: datetime(year: 2024, month: 8, day: 6),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 88,
  ),
  (
    title: "Drivetrain v1 - Troubleshooting",
    type: "build",
    date: datetime(year: 2024, month: 8, day: 9),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Makhi",
    body: 90,
  ),
  (
    title: "Drivetrain v1 - Driver Control",
    type: "program",
    date: datetime(year: 2024, month: 8, day: 10),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 94,
  ),
  (
    title: "Drivetrain v1",
    type: "test",
    date: datetime(year: 2024, month: 8, day: 10),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Makhi",
    body: 101,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "identify",
    date: datetime(year: 2024, month: 8, day: 14),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Anders",
    witnessed: "Eric",
    body: 105,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "understand",
    date: datetime(year: 2024, month: 8, day: 14),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Jin",
    witnessed: "Rory",
    body: 107,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "brainstorm",
    date: datetime(year: 2024, month: 8, day: 15),
    attendance: ("Ajibola", "Ishika"),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 109,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "select",
    date: datetime(year: 2024, month: 8, day: 15),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Jin",
      "Rory",
      "Makhi",
    ),
    designed: "Eric",
    witnessed: "Ishika",
    body: 112,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "plan",
    date: datetime(year: 2024, month: 8, day: 15),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 114,
  ),
  (
    title: "Towers & Bracing",
    type: "build",
    date: datetime(year: 2024, month: 8, day: 16),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Makhi",
    witnessed: "Rory",
    body: 119,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "build",
    date: datetime(year: 2024, month: 8, day: 17),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Makhi",
    body: 121,
  ),
  (
    title: "Mobile Goal Clamp v1 - Troubleshooting",
    type: "build",
    date: datetime(year: 2024, month: 8, day: 24),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Makhi",
    body: 125,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "program",
    date: datetime(year: 2024, month: 8, day: 24),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Ishika",
    witnessed: "Ajibola",
    body: 127,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "test",
    date: datetime(year: 2024, month: 8, day: 24),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Anders",
    body: 129,
  ),
  (
    title: "Intake v1",
    type: "identify",
    date: datetime(year: 2024, month: 8, day: 30),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Anders",
    body: 133,
  ),
  (
    title: "Intake v1",
    type: "understand",
    date: datetime(year: 2024, month: 8, day: 30),
    attendance: ("Ajibola", "Ishika", "Eric", "Rory", "Makhi"),
    designed: "Jin",
    witnessed: "Rory",
    body: 135,
  ),
  (
    title: "Intake v1",
    type: "brainstorm",
    date: datetime(year: 2024, month: 8, day: 31),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Jin",
    body: 137,
  ),
  (
    title: "September Planning",
    type: "management",
    date: datetime(year: 2024, month: 9, day: 1),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 139,
  ),
  (
    title: "Intake v1",
    type: "select",
    date: datetime(year: 2024, month: 9, day: 1),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Jin",
      "Rory",
      "Makhi",
    ),
    designed: "Rory",
    witnessed: "Ishika",
    body: 141,
  ),
  (
    title: "Intake v1",
    type: "plan",
    date: datetime(year: 2024, month: 9, day: 2),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 143
  )
)

#let full-entry-list = entry-list-1