#let entry-list-1 = (
  (
    title: "Pre-Reveal Reflection",
    type: "identify",
    date: datetime(year: 2024, month: 4, day: 20),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Jin",
    body: 1,
  ),
  (
    title: "Reveal Video Thoughts",
    type: "identify",
    date: datetime(year: 2024, month: 4, day: 27),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Jin",
    body: 4,
  ),
  (
    title: "Game Challenge - Rules Analysis",
    type: "identify",
    date: datetime(year: 2024, month: 4, day: 30),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Jin",
    body: 7,
  ),
  (
    title: "Game Challenge - Strategy Analysis",
    type: "identify",
    date: datetime(year: 2024, month: 4, day: 30),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Jin",
    body: 17,
  ),
  (
    title: "High Stakes Season Planning",
    type: "management",
    date: datetime(year: 2024, month: 4, day: 30),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Jin",
    body: 19,
  ),
  (
    title: "June Planning",
    type: "management",
    date: datetime(year: 2024, month: 6, day: 14),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Rory",
    body: 21,
  ),
  (
    title: "Overall Robot Plan v1",
    type: "brainstorm",
    date: datetime(year: 2024, month: 6, day: 14),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Jin",
    witnessed: "Anders",
    body: 22,
  ),
  (
    title: "Overall Robot Plan v1",
    type: "select",
    date: datetime(year: 2024, month: 6, day: 15),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Jin",
      "Rory",
      "Makhi",
    ),
    designed: "Rory",
    witnessed: "Ishika",
    body: 25,
  ),
  (
    title: "Overall Robot Plan v1",
    type: "plan",
    date: datetime(year: 2024, month: 6, day: 15),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Jin",
      "Rory",
      "Makhi",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 27,
  ),
  (
    title: "Kanban Board",
    type: "management",
    date: datetime(year: 2024, month: 6, day: 16),
    attendance: ("Ajibola", "Ishika", "Eric", "Rory", "Makhi"),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 28,
  ),
  (
    title: "Drivetrain v1",
    type: "identify",
    date: datetime(year: 2024, month: 6, day: 16),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 31,
  ),
  (
    title: "Drivetrain v1",
    type: "understand",
    date: datetime(year: 2024, month: 6, day: 16),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Jin",
    witnessed: "Eric",
    body: 33,
  ),
  (
    title: "Drivetrain v1 - Drive Configurations",
    type: "brainstorm",
    date: datetime(year: 2024, month: 6, day: 22),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Eric",
    body: 35,
  ),
  (
    title: "Drivetrain v1 - Drive Configurations",
    type: "select",
    date: datetime(year: 2024, month: 6, day: 22),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Makhi",
    witnessed: "Ishika",
    body: 37,
  ),
  (
    title: "Drivetrain v1 - Wheel Types",
    type: "brainstorm",
    date: datetime(year: 2024, month: 6, day: 23),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Rory",
    body: 39,
  ),
  (
    title: "Drivetrain v1 - Wheel Types",
    type: "select",
    date: datetime(year: 2024, month: 6, day: 24),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ishika",
    witnessed: "Eric",
    body: 43,
  ),
  (
    title: "Drivetrain v1 - Gear Ratio",
    type: "brainstorm",
    date: datetime(year: 2024, month: 6, day: 28),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Makhi",
    witnessed: "Jin",
    body: 45,
  ),
  (
    title: "Drivetrain v1 - Gear Ratio",
    type: "select",
    date: datetime(year: 2024, month: 6, day: 29),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Rory",
    witnessed: "Ishika",
    body: 47,
  ),
  (
    title: "Drivetrain v1",
    type: "plan",
    date: datetime(year: 2024, month: 6, day: 29),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 49,
  ),
  (
    title: "Game Manual v1.0 Update",
    type: "identify",
    date: datetime(year: 2024, month: 7, day: 1),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Ishika",
    body: 57,
  ),
  (
    title: "July & August Planning",
    type: "management",
    date: datetime(year: 2024, month: 7, day: 26),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 61,
  ),
  (
    title: "Drivetrain v1",
    type: "build",
    date: datetime(year: 2024, month: 7, day: 26),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Makhi",
    body: 63,
  ),
  (
    title: "GitHub Workflows",
    type: "program",
    date: datetime(year: 2024, month: 8, day: 3),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 73,
  ),
  (
    title: "The Minnesota Signature Event Observations",
    type: "identify",
    date: datetime(year: 2024, month: 8, day: 6),
    attendance: ("Jin", "Ishika", "Eric"),
    designed: "Jin",
    witnessed: "Ishika",
    body: 79,
  ),
  (
    title: "Overall Robot Plan v2",
    type: "brainstorm",
    date: datetime(year: 2024, month: 8, day: 6),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 86,
  ),
  (
    title: "Overall Robot Plan v2",
    type: "select",
    date: datetime(year: 2024, month: 8, day: 6),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 88,
  ),
  (
    title: "Drivetrain v1 - Troubleshooting",
    type: "build",
    date: datetime(year: 2024, month: 8, day: 9),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Makhi",
    body: 90,
  ),
  (
    title: "Drivetrain v1 - Driver Control",
    type: "program",
    date: datetime(year: 2024, month: 8, day: 10),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 94,
  ),
  (
    title: "Drivetrain v1",
    type: "test",
    date: datetime(year: 2024, month: 8, day: 10),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Makhi",
    body: 101,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "identify",
    date: datetime(year: 2024, month: 8, day: 14),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Anders",
    witnessed: "Eric",
    body: 105,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "understand",
    date: datetime(year: 2024, month: 8, day: 14),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Jin",
    witnessed: "Rory",
    body: 107,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "brainstorm",
    date: datetime(year: 2024, month: 8, day: 15),
    attendance: ("Ajibola", "Ishika"),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 109,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "select",
    date: datetime(year: 2024, month: 8, day: 15),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Jin",
      "Rory",
      "Makhi",
    ),
    designed: "Eric",
    witnessed: "Ishika",
    body: 112,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "plan",
    date: datetime(year: 2024, month: 8, day: 15),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 114,
  ),
  (
    title: "Towers & Bracing",
    type: "build",
    date: datetime(year: 2024, month: 8, day: 16),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Makhi",
    witnessed: "Rory",
    body: 119,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "build",
    date: datetime(year: 2024, month: 8, day: 17),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Makhi",
    body: 121,
  ),
  (
    title: "Mobile Goal Clamp v1 - Troubleshooting",
    type: "build",
    date: datetime(year: 2024, month: 8, day: 24),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Makhi",
    body: 125,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "program",
    date: datetime(year: 2024, month: 8, day: 24),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Ishika",
    witnessed: "Ajibola",
    body: 127,
  ),
  (
    title: "Mobile Goal Clamp v1",
    type: "test",
    date: datetime(year: 2024, month: 8, day: 24),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Anders",
    body: 129,
  ),
  (
    title: "Intake v1",
    type: "identify",
    date: datetime(year: 2024, month: 8, day: 30),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Anders",
    body: 133,
  ),
  (
    title: "Intake v1",
    type: "understand",
    date: datetime(year: 2024, month: 8, day: 30),
    attendance: ("Ajibola", "Ishika", "Eric", "Rory", "Makhi"),
    designed: "Jin",
    witnessed: "Rory",
    body: 135,
  ),
  (
    title: "Intake v1",
    type: "brainstorm",
    date: datetime(year: 2024, month: 8, day: 31),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Jin",
    body: 137,
  ),
  (
    title: "September Planning",
    type: "management",
    date: datetime(year: 2024, month: 9, day: 1),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 139,
  ),
  (
    title: "Intake v1",
    type: "select",
    date: datetime(year: 2024, month: 9, day: 1),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Jin",
      "Rory",
      "Makhi",
    ),
    designed: "Rory",
    witnessed: "Ishika",
    body: 141,
  ),
  (
    title: "Intake v1",
    type: "plan",
    date: datetime(year: 2024, month: 9, day: 2),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 143
  )
)

#let entry-list-2 = (
  (
    title: "Game Manual v2.0 Update",
    type: "identify",
    date: datetime(year: 2024, month: 9, day: 6),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 150,
  ),
  (
    title: "Intake v1",
    type: "build",
    date: datetime(year: 2024, month: 9, day: 6),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Jin",
    witnessed: "Makhi",
    body: 153,
  ),
  (
    title: "Intake v1 - Troubleshooting",
    type: "build",
    date: datetime(year: 2024, month: 9, day: 21),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Anders",
    witnessed: "Makhi",
    body: 162,
  ),
  (
    title: "Intake v1",
    type: "program",
    date: datetime(year: 2024, month: 9, day: 27),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Ishika",
    witnessed: "Ajibola",
    body: 164,
  ),
  (
    title: "Intake v1",
    type: "test",
    date: datetime(year: 2024, month: 9, day: 27),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Ajibola",
    witnessed: "Makhi",
    body: 165,
  ),
  (
    title: "Autonomous - Area 53 Scrimmage",
    type: "program",
    date: datetime(year: 2024, month: 9, day: 28),
    attendance: ("Jin", "Ishika", "Makhi", "Eric", "Rory", "Anders"),
    designed: "Ishika",
    witnessed: "Ajibola",
    body: 169,
  ),
  (
    title: "Area 53 Scrimmage",
    type: "competition",
    date: datetime(year: 2024, month: 9, day: 28),
    attendance: ("Jin", "Ishika", "Makhi", "Eric", "Rory", "Anders"),
    designed: "Jin",
    witnessed: "Eric",
    body: 171,
  ),
  (
    title: "October Planning",
    type: "management",
    date: datetime(year: 2024, month: 10, day: 3),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 179,
  ),
  (
    title: "Mobile Goal Clamp v2",
    type: "identify",
    date: datetime(year: 2024, month: 10, day: 3),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Makhi",
    witnessed: "Rory",
    body: 181,
  ),
  (
    title: "Mobile Goal Clamp v2",
    type: "plan",
    date: datetime(year: 2024, month: 10, day: 3),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 183,
  ),
  (
    title: "Mobile Goal Clamp v2",
    type: "build",
    date: datetime(year: 2024, month: 10, day: 4),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Rory",
    witnessed: "Jin",
    body: 188,
  ),
  (
    title: "Mobile Goal Clamp v2 - Troubleshooting",
    type: "build",
    date: datetime(year: 2024, month: 10, day: 5),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Rory",
    witnessed: "Anders",
    body: 190,
  ),
  (
    title: "Mobile Goal Clamp v2",
    type: "test",
    date: datetime(year: 2024, month: 10, day: 5),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Ishika",
    body: 192,
  ),
  (
    title: "Redirect Mechanism v1",
    type: "identify",
    date: datetime(year: 2024, month: 10, day: 10),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Anders",
    body: 196,
  ),
  (
    title: "Redirect Mechanism v1",
    type: "understand",
    date: datetime(year: 2024, month: 10, day: 10),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Rory",
      "Makhi",
      "Anders",
    ),
    designed: "Jin",
    witnessed: "Eric",
    body: 198,
  ),
  (
    title: "Redirect Mechanism v1",
    type: "brainstorm",
    date: datetime(year: 2024, month: 10, day: 10),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Rory",
    witnessed: "Jin",
    body: 200,
  ),
  (
    title: "Redirect Mechanism v1",
    type: "select",
    date: datetime(year: 2024, month: 10, day: 10),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Jin",
      "Rory",
      "Makhi",
    ),
    designed: "Rory",
    witnessed: "Ishika",
    body: 202,
  ),
  (
    title: "Redirect Mechanism v1",
    type: "plan",
    date: datetime(year: 2024, month: 10, day: 10),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 204,
  ),
  (
    title: "Redirect Mechanism v1",
    type: "build",
    date: datetime(year: 2024, month: 10, day: 11),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Anders",
    witnessed: "Eric",
    body: 210,
  ),
  (
    title: "Redirect Mechanism v1",
    type: "program",
    date: datetime(year: 2024, month: 10, day: 18),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Ishika",
    witnessed: "Ajibola",
    body: 217,
  ),
  (
    title: "Redirect Mechanism v1",
    type: "test",
    date: datetime(year: 2024, month: 10, day: 18),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Rory",
    witnessed: "Eric",
    body: 218,
  ),
  (
    title: "Dulaney Royal Rumble",
    type: "competition",
    date: datetime(year: 2024, month: 10, day: 19),
    attendance: ("Jin", "Ishika", "Makhi", "Eric", "Rory", "Anders"),
    designed: "Jin",
    witnessed: "Anders",
    body: 222,
  ),
  (
    title: "Ladybrown v1",
    type: "identify",
    date: datetime(year: 2024, month: 10, day: 23),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Anders",
    witnessed: "Eric",
    body: 229,
  ),
  (
    title: "Ladybrown v1",
    type: "understand",
    date: datetime(year: 2024, month: 10, day: 23),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Rory",
      "Makhi",
      "Anders",
    ),
    designed: "Jin",
    witnessed: "Anders",
    body: 231,
  ),
  (
    title: "Ladybrown v1",
    type: "brainstorm",
    date: datetime(year: 2024, month: 10, day: 24),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Makhi",
    witnessed: "Jin",
    body: 233,
  ),
  (
    title: "Ladybrown v1",
    type: "select",
    date: datetime(year: 2024, month: 10, day: 24),
    attendance: (
      "Ajibola",
      "Ishika",
      "Eric",
      "Jin",
      "Rory",
      "Makhi",
    ),
    designed: "Makhi",
    witnessed: "Ishika",
    body: 235,
  ),
  (
    title: "Ladybrown v1",
    type: "plan",
    date: datetime(year: 2024, month: 10, day: 24),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 237,
  ),
  (
    title: "Overall Robot Plan v3",
    type: "identify",
    date: datetime(year: 2024, month: 10, day: 25),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Makhi",
    witnessed: "Rory",
    body: 242,
  ),
  (
    title: "Overall Robot Plan v3",
    type: "plan",
    date: datetime(year: 2024, month: 10, day: 25),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 244,
  ),
  (
    title: "Intake v2",
    type: "identify",
    date: datetime(year: 2024, month: 10, day: 26),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Anders",
    witnessed: "Eric",
    body: 245,
  ),
  (
    title: "Intake v2",
    type: "plan",
    date: datetime(year: 2024, month: 10, day: 26),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Jin",
    witnessed: "Ajibola",
    body: 247,
  ),
  (
    title: "November Planning",
    type: "management",
    date: datetime(year: 2024, month: 11, day: 1),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 253,
  ),
  (
    title: "Drivetrain v1 - Troubleshooting",
    type: "build",
    date: datetime(year: 2024, month: 11, day: 1),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Rory",
    witnessed: "Eric",
    body: 255,
  ),
  (
    title: "Ladybrown v1",
    type: "build",
    date: datetime(year: 2024, month: 11, day: 1),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Makhi",
    witnessed: "Jin",
    body: 256,
  ),
  (
    title: "Intake v2",
    type: "build",
    date: datetime(year: 2024, month: 11, day: 1),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Anders",
    witnessed: "Makhi",
    body: 262,
  ),
  (
    title: "Ladybrown v1",
    type: "program",
    date: datetime(year: 2024, month: 11, day: 15),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
    ),
    designed: "Ajibola",
    witnessed: "Ishika",
    body: 266,
  ),
  (
    title: "Ladybrown v1",
    type: "test",
    date: datetime(year: 2024, month: 11, day: 15),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Anders",
    witnessed: "Makhi",
    body: 278,
  ),
  (
    title: "Intake v2",
    type: "test",
    date: datetime(year: 2024, month: 11, day: 15),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Rory",
    body: 282,
  ),
  (
    title: "Capital Beltway Challenge",
    type: "competition",
    date: datetime(year: 2024, month: 11, day: 16),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Anders",
    witnessed: "Rory",
    body: 286,
  ),
  (
    title: "Mobile Goal Clamp v2 - Troubleshooting",
    type: "build",
    date: datetime(year: 2024, month: 11, day: 18),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Eric",
      "Rory",
      "Anders",
    ),
    designed: "Rory",
    witnessed: "Ishika",
    body: 293,
  ),
  (
    title: "Mobile Goal Clamp v2 - Re-Test",
    type: "test",
    date: datetime(year: 2024, month: 11, day: 19),
    attendance: (
      "Ajibola",
      "Jin",
      "Ishika",
      "Makhi",
      "Rory",
      "Eric",
      "Anders",
    ),
    designed: "Eric",
    witnessed: "Anders",
    body: 296,
  ),
)

#let full-entry-list = entry-list-1 + entry-list-2